"""
Tests for the AI/RAG recommendation layer and the control→standard map.

Recommendations themselves are generated by the LLM over retrieved documents,
so they are not deterministically asserted here; instead we verify the
control→standard reference map and the deterministic offline fallback.
"""

from app.llm import recommendation
from app.schemas.control import Finding


def _f(control_type, field, severity="high"):
    return Finding(
        control_type=control_type, field=field, severity=severity,
        expected="x", actual="y", description="d",
    )


def test_recommendations_offline_fallback(monkeypatch):
    # When the LLM is offline, a deterministic summary is returned (no crash).
    monkeypatch.setattr(recommendation, "is_ollama_up", lambda: False)
    text, source = recommendation.generate_recommendations(
        "HOST-1", [_f("antivirus", "av_installed", "critical")]
    )
    assert source == "fallback"
    assert "HOST-1" in text


def test_recommendations_empty_is_none():
    text, source = recommendation.generate_recommendations("HOST-1", [])
    assert source == "none"
    assert "compliant" in text.lower()
