// API contract types — mirror the backend Pydantic schemas.

export type ValidationStatus = "PASS" | "WARNING" | "FAIL" | "NO_DATA";
export type Severity = "critical" | "high" | "medium" | "low";
export type ControlType = "antivirus" | "edr" | "dlp" | "bitlocker";

export interface User {
  id: number;
  username: string;
  email: string;
  role: string;
  is_active: number;
  created_at: string;
}

export interface Token {
  access_token: string;
  token_type: string;
  expires_in: number;
}

export interface Finding {
  control_type: ControlType;
  field: string;
  expected: unknown;
  actual: unknown;
  severity: Severity;
  description: string;
}

export interface ControlValidation {
  control_type: ControlType;
  label: string;
  status: ValidationStatus;
  present: boolean;
  score: number;
  total_fields: number;
  passed_fields: number;
  findings: Finding[];
}

export interface AssetOut {
  hostname: string;
  ip_address: string;
  operating_system: string;
  business_owner: string;
}

export interface ControlRecord {
  hostname: string;
  [key: string]: unknown;
}

export interface EndpointSummary {
  hostname: string;
  ip_address: string;
  operating_system: string;
  business_owner: string;
  status: ValidationStatus;
  compliance_score: number;
  critical_findings: number;
  high_findings: number;
  total_findings: number;
  control_statuses: Record<ControlType, ValidationStatus>;
}

export interface CisReference {
  safeguard: string;
  title: string;
  function: string;
}

export interface Recommendation {
  control_type: ControlType;
  field: string;
  severity: Severity;
  title: string;
  finding: string;
  observed: string;
  required: string;
  why: string;
  blueprint_rule: string;
  policy_reference: string;
  cis: CisReference | null;
  steps: string[];
}

export interface EndpointDetail {
  asset: AssetOut;
  status: ValidationStatus;
  compliance_score: number;
  controls: ControlValidation[];
  evidence: ControlRecord;
  findings: Finding[];
  // Recommendations are generated by the AI (RAG) on demand — fetched separately.
  ai_available: boolean;
}

export interface PaginatedEndpoints {
  items: EndpointSummary[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}

export interface ControlComplianceStat {
  control_type: ControlType;
  label: string;
  compliance_rate: number;
  pass_count: number;
  warning_count: number;
  fail_count: number;
  no_data_count: number;
}

export interface TrendPoint {
  label: string;
  score: number;
}

export interface DashboardSummary {
  total_endpoints: number;
  overall_compliance_score: number;
  endpoint_status_breakdown: Record<string, number>;
  findings_by_severity: Record<Severity, number>;
  critical_findings: number;
  high_risk_findings: number;
  per_control: ControlComplianceStat[];
  top_findings: Finding[];
  trend: TrendPoint[];
}

export interface ChatSource {
  kind: string; // engine | database | blueprint | policy | standard | inventory
  label: string;
}

export interface ChatTableRow {
  hostname: string | null;
  values: Record<string, unknown>;
}

export interface ChatResponse {
  status: string;
  answer_type: string; // endpoint | fleet_metric | list | policy | explanation | clarification
  message: string;
  use_case: string | null;
  hostname: string | null;
  ip: string | null;
  compliant: boolean | null;
  findings: Finding[];
  ai_recommendations: string | null;
  table: ChatTableRow[];
  sources: ChatSource[];
  ai_available: boolean;
  data: Record<string, unknown> | null;
}

export interface EndpointFilters {
  owners: string[];
  operating_systems: string[];
  statuses: ValidationStatus[];
  controls: ControlType[];
}

export interface BlueprintRuleView {
  field: string;
  operator: string;
  operator_label: string;
  expected: unknown;
  severity: Severity;
  description: string;
  cis: CisReference | null;
  policy_reference: string;
}

export interface ControlBlueprint {
  control_type: ControlType;
  label: string;
  rule_count: number;
  golden_image: Record<string, string> | null;
  rules: BlueprintRuleView[];
}

export interface PolicyDoc {
  id: string;
  title: string;
  text: string;
}

export interface BlueprintView {
  total_rules: number;
  controls: ControlBlueprint[];
  policies: PolicyDoc[];
  standard_name: string;
  standard_controls: number;
  standard_safeguards: number;
}

export interface AuditEvent {
  id: number;
  occurred_at: string;
  username: string;
  action: string;
  detail: string;
}

export interface AuditTrail {
  total: number;
  counts_by_action: Record<string, number>;
  events: AuditEvent[];
}

export type FindingStatus = "in_progress" | "risk_accepted" | "false_positive";

export interface FindingState {
  hostname: string;
  control_type: ControlType;
  field: string;
  status: FindingStatus;
  justification: string;
  owner: string;
  expires_at: string | null;
  updated_by: string;
  updated_at: string;
  expired: boolean;
}

export interface EvidenceSource {
  control_type: string;
  label: string;
  source_file: string;
  loaded_at: string | null;
  present: boolean;
  key: string;
}

export interface EvidenceSources {
  hostname: string;
  sources: EvidenceSource[];
}
