"""Endpoint list/detail contracts returned by the API."""

from pydantic import BaseModel

from app.schemas.control import ControlRecord, Finding


class AssetOut(BaseModel):
    hostname: str
    ip_address: str
    operating_system: str
    business_owner: str


class ControlValidation(BaseModel):
    """Result of validating one control against the blueprint."""

    control_type: str
    label: str
    status: str  # ValidationStatus value
    present: bool
    score: float  # 0..100, share of this control's fields that pass
    total_fields: int
    passed_fields: int
    findings: list[Finding] = []


class EndpointSummary(BaseModel):
    """One row in the endpoints table."""

    hostname: str
    ip_address: str
    operating_system: str
    business_owner: str
    status: str  # worst control status
    compliance_score: float  # 0..100 across all controls
    critical_findings: int
    high_findings: int
    total_findings: int
    control_statuses: dict[str, str]  # control_type -> status


class EndpointDetail(BaseModel):
    asset: AssetOut
    status: str
    compliance_score: float
    controls: list[ControlValidation]
    evidence: ControlRecord
    findings: list[Finding]  # all findings, severity-sorted (deterministic)
    # Recommendations are generated by the AI via RAG on demand — fetched from
    # GET /endpoints/{hostname}/recommendations, not carried here.
    ai_available: bool = False  # whether the AI recommendation layer is online


class PaginatedEndpoints(BaseModel):
    items: list[EndpointSummary]
    total: int
    page: int
    page_size: int
    total_pages: int
