"""
Structured, grounded remediation recommendation.

Every recommendation is derived deterministically from a finding and the
remediation knowledge base — it is anchored first in OUR blueprint rule and
OUR control policy/baseline, with a CIS Safeguard cited only as a supporting
reference. Nothing here is generated by an LLM, so it can never hallucinate a
control number or a policy.
"""

from typing import Optional

from pydantic import BaseModel


class CisReference(BaseModel):
    safeguard: str  # e.g. "10.2"
    title: str  # e.g. "Configure Automatic Anti-Malware Signature Updates"
    function: str  # e.g. "Devices / Protect"


class Recommendation(BaseModel):
    control_type: str
    field: str
    severity: str

    title: str  # the remediation headline / action
    finding: str  # what is wrong (grounded in the finding)
    observed: str  # actual value
    required: str  # blueprint-expected value

    why: str  # rationale + why this severity
    blueprint_rule: str  # the exact rule that failed, in plain language
    policy_reference: str  # OUR control policy / baseline reference
    cis: Optional[CisReference] = None  # supporting standard reference

    steps: list[str]  # concrete remediation steps
